# dragon_input demo — DEVICE-AWARE PROMPTS
#
# Thesis: you bind actions once; dragon_input shows the right button glyph for
# whatever device the player last touched. Press keys or a controller (or move
# WASD vs the left stick) and watch every prompt swap instantly between keyboard
# and controller art — with zero per-device code in this file.

require 'app/drenv_bundle.rb' # generated by `drenv add path:.. -n dragon_input`

# The four actions we prompt for. Each is bound to BOTH a key and a controller
# input — that's the whole point: one binding table, prompts follow the device.
ACTIONS = [:move, :fire, :jump, :interact].freeze

DEVICE_LABELS = {
  keyboard:    'Keyboard & Mouse',
  xbox:        'Xbox Controller',
  playstation: 'PlayStation Controller',
  switch:      'Nintendo Switch'
}.freeze

DEVICE_COLORS = {
  keyboard:    { r: 90,  g: 150, b: 230 },
  xbox:        { r: 110, g: 200, b: 110 },
  playstation: { r: 90,  g: 150, b: 230 },
  switch:      { r: 230, g: 100, b: 100 }
}.freeze

def configure_input
  DragonInput.setup do |c|
    c.action_set :gameplay do |s|
      s.analog  :move,     controller: :left_analog, keyboard: [:wasd, :arrows]
      s.digital :fire,     controller: :r2, keyboard: :space
      s.digital :jump,     controller: :a,  keyboard: :j
      s.digital :interact, controller: :x,  keyboard: :e
    end
  end
end

def tick(args)
  if Kernel.tick_count == 0
    configure_input
    args.state.field = { x: 340, y: 70, w: 600, h: 190 }
    args.state.dot = { x: 640, y: 165, w: 28, h: 28 }
    args.state.flash = {}
  end

  DragonInput.tick(args)
  update(args)
  render(args)
end

def update(args)
  # The only interaction: move a dot and press the actions. Using keyboard vs a
  # controller here is what flips the device the prompts follow.
  move = DragonInput.axis(:one, :move)
  f = args.state.field
  d = args.state.dot
  d.x = (d.x + move[:x] * 6).clamp(f.x, f.x + f.w - d.w)
  d.y = (d.y + move[:y] * 6).clamp(f.y, f.y + f.h - d.h)

  [:fire, :jump, :interact].each do |a|
    args.state.flash[a] = Kernel.tick_count if DragonInput.just_pressed?(:one, a)
  end
end

# ---- Render ----------------------------------------------------------------

def render(args)
  args.outputs.background_color = [16, 16, 22]
  style = DragonInput.glyph_style(:one)

  render_header(args)
  render_device_banner(args, style)
  render_prompt_legend(args, style)
  render_field(args)
  render_footer(args)

  # Persistent current-device icon, bottom-right.
  DragonInput.render_device_glyph(args, :one, { x: 1184, y: 40, w: 72, h: 72 })
end

def render_header(args)
  args.outputs.labels << { x: 640, y: 690, text: 'dragon_input', size_px: 34,
                           alignment_enum: 1, r: 235, g: 235, b: 245 }
  args.outputs.labels << { x: 640, y: 655,
                           text: 'Bind actions once — the prompts follow the device you last used.',
                           size_px: 20, alignment_enum: 1, r: 170, g: 172, b: 185 }
end

# The star of the show: a big banner naming the device the prompts are tracking.
def render_device_banner(args, style)
  color = DEVICE_COLORS[style] || DEVICE_COLORS[:keyboard]
  label = DEVICE_LABELS[style] || style.to_s

  args.outputs.labels << { x: 640, y: 600, text: 'NOW SHOWING PROMPTS FOR',
                           size_px: 14, alignment_enum: 1, r: 130, g: 132, b: 145 }
  # Vertically center the text on y=560 so we know its extent, then rule under it.
  args.outputs.labels << { x: 640, y: 560, text: label, size_px: 40,
                           alignment_enum: 1, vertical_alignment_enum: 1, **color }
  args.outputs.sprites << { x: 470, y: 532, w: 340, h: 3, path: :solid, **color }
end

# One cell per action: device-aware glyph + name, lit while the action is active.
def render_prompt_legend(args, style)
  cell_w = 180
  start_x = 640 - (ACTIONS.size * cell_w / 2)

  ACTIONS.each_with_index do |action, i|
    cx = start_x + (i * cell_w) + (cell_w / 2)
    active = action_active?(args, action)

    if active
      args.outputs.sprites << { x: cx - 58, y: 360, w: 116, h: 130,
                                path: :solid, r: 45, g: 52, b: 78 }
    end

    DragonInput.render_glyph(args, :one, action, { x: cx - 40, y: 400, w: 80, h: 80 })

    args.outputs.labels << { x: cx, y: 388, text: action.to_s, size_px: 20,
                             alignment_enum: 1,
                             r: active ? 255 : 200, g: active ? 230 : 200,
                             b: active ? 130 : 210 }
  end

  args.outputs.labels << { x: 640, y: 320,
                           text: '(same glyph slots, different art — nothing in the game code changed)',
                           size_px: 15, alignment_enum: 1, r: 120, g: 122, b: 135 }
end

def render_field(args)
  f = args.state.field
  args.outputs.borders << f.merge(r: 70, g: 74, b: 96)
  args.outputs.sprites << args.state.dot.merge(path: :solid, r: 240, g: 200, b: 90)
  args.outputs.labels << { x: f.x + f.w / 2, y: f.y + f.h + 4,
                           text: 'move me', size_px: 14, alignment_enum: 1,
                           r: 120, g: 122, b: 135 }
end

def render_footer(args)
  args.outputs.labels << { x: 640, y: 40,
                           text: 'Move: WASD / arrows / left stick    Fire: Space / RT    Jump: J / A    Interact: E / X',
                           size_px: 16, alignment_enum: 1, r: 150, g: 152, b: 165 }
  args.outputs.labels << { x: 640, y: 18,
                           text: "backend: #{DragonInput.backend_name}   —   touch a controller, then the keyboard, and watch the prompts flip",
                           size_px: 13, alignment_enum: 1, r: 105, g: 107, b: 120 }
end

def action_active?(args, action)
  if action == :move
    v = DragonInput.axis(:one, :move)
    (v[:x].abs + v[:y].abs) > 0.01
  else
    recent = args.state.flash[action]
    (DragonInput.pressed?(:one, action) || (recent && (Kernel.tick_count - recent) < 12))
  end
end
